<?php

/**
 * Generated by ZF2ModuleCreator
 */
namespace Album;

//use Zend\ServiceManager\Factory\InvokableFactory;

return array(

    'doctrine' => array(
        'driver' => array(
            'album_entity' => array(
                'class' =>'Doctrine\ORM\Mapping\Driver\AnnotationDriver',
                'paths' => array(__DIR__ . '/../src/Album/Entity')
            ),
            'orm_default' => array(
                'drivers' => array(
                    'Album\Entity' => 'album_entity',
                )
            )
        )
    ),

    'view_manager' => array(
        'template_path_stack' => array(
            __DIR__ . '/../view',
        ),
    ),

    'controllers' => array(
        'invokables' => array(
            'Album\Controller\Album' => 'Album\Controller\AlbumController',
        ),
    ),

    'view_helpers' => array(
        'invokables' => array(
            'showMessages' => 'Album\View\Helper\ShowMessages',
        ),
    ),

    'service_manager' => array(

    ),

    'router' => array(

        'routes' => array(
            'album' => array(
                'type' => 'Segment',
                'options' => array(
                   'route' => '/[:action[/][:id]]',
                    'constraints' => array(
                        'action' => '[a-zA-Z][a-zA-Z0-9_-]*',
                        'id' => '[0-9]+',
                    ),
                    'defaults' => array(
                        'controller' => 'Album\Controller\Album',
                        'action'     => 'index',
                    )
                )
            )
        ),

    )

);