<?php
$title = 'Edit album';
$this->headTitle($title);
?>
    <h1><?= $this->escapeHtml($title) ?></h1>
<?php

echo $this->flashMessenger()->render('error',   ['alert', 'alert-dismissible', 'alert-danger']);
echo $this->flashMessenger()->render('info',    ['alert', 'alert-dismissible', 'alert-info']);
echo $this->flashMessenger()->render('default', ['alert', 'alert-dismissible', 'alert-warning']);
echo $this->flashMessenger()->render('success', ['alert', 'alert-dismissible', 'alert-success']);
// This provides a default CSS class and placeholder text for the title element:
echo '<img style="width:100px" src="'. $picture .'">';
$picture = $form->get('picture');
$picture->setAttribute('class', 'form-control');

$album = $form->get('title');
$album->setAttribute('class', 'form-control');
$album->setAttribute('placeholder', 'Album title');

// This provides a default CSS class and placeholder text for the artist element:
$artist = $form->get('artist');
$artist->setAttribute('class', 'form-control');
$artist->setAttribute('placeholder', 'Artist');

// This provides CSS classes for the submit button:
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('album', ['action' => 'edit', 'id' => $id]));
$form->prepare();

echo $this->form()->openTag($form);
?>
<?php // Wrap the elements in divs marked as form groups, and render the
// label, element, and errors separately within ?>
    <div class="form-group">
        <?= $this->formLabel($picture) ?>
        <?= $this->formElement($picture) ?>
        <?= $this->formElementErrors()->render($picture, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($album) ?>
        <?= $this->formElement($album) ?>
        <?= $this->formElementErrors()->render($album, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($artist) ?>
        <?= $this->formElement($artist) ?>
        <?= $this->formElementErrors()->render($artist, ['class' => 'help-block']) ?>
    </div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();